stages:
  extract_data:
    cmd: python pipeline/extract_data/extract_data.py
    deps:
    - pipeline/extract_data/extract_data.py
    outs:
    - data/raw
  prepare:
    cmd: python pipeline/prepare/prepare.py data/raw/train.tfrecord data/raw/test.tfrecord
    deps:
    - data/raw/test.tfrecord
    - data/raw/train.tfrecord
    - pipeline/prepare/prepare.py
    params:
    - prepare.n_classes
    - prepare.norm_const
    - prepare.train_samples
    - prepare.test_samples
    outs:
    - data/prepared
  train:
    cmd: python pipeline/train/train.py data/prepared/processed.npz
      schema/plot.json pipeline/train/
    deps:
    - data/prepared/processed.npz
    - pipeline/train/model.py
    - pipeline/train/train.py
    - schema/plot.json
    params:
    - train.epochs
    - train.metrics
    - train.n_classes
    - train.optimizer
    - train.batch_size
    - train.shuffle_buffer_size
    outs:
    - model/LeNet_checkpoints
    plots:
    - results/train_stats_acc.json:
        cache: false
    - results/train_stats_loss.json:
        cache: false
    - results/train_stats_mse.json:
        cache: false
  evaluate:
    cmd: python pipeline/evaluate/evaluate.py data/prepared/processed.npz pipeline/train/
      model/LeNet_checkpoints/best.ckpt
    deps:
    - model/LeNet_checkpoints
    - pipeline/evaluate/evaluate.py
    - pipeline/train/model.py
    params:
    - evaluate.class_names
    - evaluate.seed
    - train.metrics
    - train.n_classes
    - train.optimizer
    metrics:
    - results/metrics.json:
        cache: false
    outs:
    - results/confusion_matrix.png
