extract:
  train_samples: 1024
  test_samples: 64

prepare:
  norm_const: 255
  n_classes: 10

train:
  n_classes: 10
  epochs: 50
  optimizer: "adam"
  metrics: ["accuracy", "mse"]

evaluate:
  seed: 2