extract:
  train_samples: 2048
  test_samples: 128

prepare:
  norm_const: 255
  n_classes: 10

train:
  n_classes: 10
  epochs: 70
  optimizer: "adam"
  metrics: ["accuracy", "mse"]

evaluate:
  seed: 2
  class_names: ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']