prepare:
  train_samples: 1024
  test_samples: 64
  norm_const: 255
  n_classes: 10

train:
  n_classes: 10
  epochs: 50
  batch_size: 16
  shuffle_buffer_size: 100
  optimizer: "adagrad"
  metrics: ["accuracy", "mse"]

evaluate:
  seed: 2
  class_names: ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']