extract:
  train_samples: 1024
  test_samples: 64

prepare:
  norm_const: 255
  n_classes: 10

train:
  n_classes: 10
  epochs: 50
  optimizer: "adagrad"

  # Choose from the below metrics to be reported for the Image classification model
  # categorical_crossentropy, categorical_hinge, kullback_leibler_divergence, accuracy, Precision, Recall
  metrics: ["categorical_crossentropy", "accuracy", "Precision", "Recall"]

evaluate:
  seed: 2
  class_names: ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']