name: fashion_mnist_train_pipeline

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install dvc[s3]
          
          pip install -r requirements.txt
           
          dvc repro 
          
          git fetch --prune --unshallow

          git diff --cached params.yaml --show-md develop >> report.md

          dvc metrics diff --show-md develop >> report.md

          vl2png results/train_stats_loss.json -s 1.5 | cml-publish --md >> report.md
          vl2png results/train_stats_acc.json -s 1.5 | cml-publish --md >> report.md
          vl2png results/train_stats_mse.json -s 1.5 | cml-publish --md >> report.md
        
          cml-send-comment report.md 